theory_name: Automated Detection of Implicit Theory
acronym: ADIT
l1_papers:
#  - 10.1109/HICSS.2014.564 # Larsen et al. (2014) - Theory Identity: A Machine-Learning Approach
  - 10.17705/1jais.00556 # Larsen et al. (2019) - Understanding the Elephant: The Discourse Approach to Boundary Identification and Corpus Construction for Theory Review Articles
online: true
depth: l2
key_constructs:
  - theory identity
  - implicit theory
cache_dir: .cache/adit_ingestion
refresh_cache: true
reset_checkpoints: true
only_ingest: true
save_ingested_citation_data: outputs/adit_as_theory_data.json
save_ingested_papers_data: outputs/adit_as_theory_papers_data.json
output_features: outputs/adit_as_theory_features.csv
max_workers: 4
